/*
 * This source file was generated by the Gradle 'init' task
 */
package com.comp2120.a3;

import com.comp2120.a3.engine.GameEngine;


/**
 * The launcher of the game, instantiates a game engine and runs it.
 *
 * @author Jason Xu
 */
public class App {
    /**
     * Entry point of the game, instantiates a game engine and runs it.
     *
     * @param args command line arguments
     * @author Jason Xu
     */
    public static void main(String[] args) {
        // Instantiate a game engine
        GameEngine engine = new GameEngine();
        // Run the game engine
        engine.start();
    }
}
